# Site Settings
title: "Alec's Very Cool and Extremely Useful Stats & Graphs"
author: "Alec Howard"
description: "A place to look at very cool and extremely useful stats and graphs made by some guy who likes Dota too much"
date_format: "%Y-%m-%d"
url: "https://abhoward.github.io"
plugins: 
  - jekyll-seo-tag
