# Site Settings
title: "Dota Data"
author: "Alec Howard"
description: "A website dedicated to providing accessible stats and graphs for professional DOTA 2 matches."
date_format: "%Y-%m-%d"
url: "https://abhoward.github.io"
theme: "jekyll-theme-midnight"
plugins: 
  - jekyll-seo-tag
