theme: jekyll-theme-midnight
title: Alec's Very Cool And Not Bad Graphs
description: A place to look at extremely cool and not at all bad graphs made by Alec, the greatest pokemon shiny hunter in NA. 
